// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuHqBaS8pqqdgAwlaDGAfpa_JlbQ83Bmk',
    appId: '1:183095058928:web:d3827e3aac1b4999cebd35',
    messagingSenderId: '183095058928',
    projectId: 'to-do-3ef2d',
    authDomain: 'to-do-3ef2d.firebaseapp.com',
    storageBucket: 'to-do-3ef2d.appspot.com',
    measurementId: 'G-7BXRW73BHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC_JU-tPRXmm7JhRx8tUrtpsG8U3IeCqc',
    appId: '1:183095058928:android:be7f872e69d1e12bcebd35',
    messagingSenderId: '183095058928',
    projectId: 'to-do-3ef2d',
    storageBucket: 'to-do-3ef2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkIkl9hEkHyw3Z-11kw2B4olSm4UFb3uI',
    appId: '1:183095058928:ios:54d8f94e83950584cebd35',
    messagingSenderId: '183095058928',
    projectId: 'to-do-3ef2d',
    storageBucket: 'to-do-3ef2d.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkIkl9hEkHyw3Z-11kw2B4olSm4UFb3uI',
    appId: '1:183095058928:ios:54d8f94e83950584cebd35',
    messagingSenderId: '183095058928',
    projectId: 'to-do-3ef2d',
    storageBucket: 'to-do-3ef2d.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
